/**
 * Application configuration constants
 */
export const CONFIG = {
    // Base URL for all data files. Set to empty string for local paths.
    // Example: 'https://raw.githubusercontent.com/kfgod/minecraft_folder/main' or ''
    BASE_URL: 'https://raw.githubusercontent.com/kfgod/minecraft_folder_data/main',
    INDEX_FILE_PATH: 'data/file_index.json',
    IMAGE_BASE_PATH: 'images',
    PLACEHOLDER_IMAGE: 'static/images/empty_slot.png',
    ENCHANTMENT_ICON: 'static/images/enchanted_book.png',
    VIEWS: {
        VERSIONS: 'versions',
        YEARS: 'years',
    },
    COLUMNS_COUNT: 9,
    NAV_PANEL_WIDTH: 280,
    LAYOUT_GAP: 40,
    DEBOUNCE_DELAY: 250,
    RESIZE_DEBOUNCE_DELAY: 100,
    TRANSITION_DELAY: 50,
    CHART_COLORS: {
        BLOCKS: 'rgba(255, 99, 132, 1)',
        BLOCKS_BG: 'rgba(255, 99, 132, 0.2)',
        ITEMS: 'rgba(54, 162, 235, 1)',
        ITEMS_BG: 'rgba(54, 162, 235, 0.2)',
        MOBS: 'rgba(255, 206, 86, 1)',
        MOBS_BG: 'rgba(255, 206, 86, 0.2)',
        EFFECTS: 'rgba(75, 192, 192, 1)',
        EFFECTS_BG: 'rgba(75, 192, 192, 0.2)',
        ADVANCEMENTS: 'rgba(255, 159, 64, 1)',
        ADVANCEMENTS_BG: 'rgba(255, 159, 64, 0.2)',
        GRID: 'rgba(255, 255, 255, 0.1)',
        TEXT: 'white',
    },
    CSS_CLASSES: {
        NO_TRANSITION: 'no-transition',
        MOBILE_LAYOUT: 'mobile-layout',
        DESKTOP_LAYOUT: 'desktop-layout',
        ACTIVE: 'active',
        VISIBLE: 'is-visible',
        SHOW_BORDERS: 'show-borders',
    },
    SELECTORS: {
        BODY: 'body',
        MAIN: 'main',
        CONTENT: '#content',
        NAV_LIST: '#nav-list',
        SEARCH_BAR: '#search-bar',
        SEARCH_CLEAR_BTN: '#search-clear-btn',
        TOGGLE_SWITCH: '.toggle-switch',
        REMOVE_DUPLICATES_CHECKBOX: '#remove-duplicates-checkbox',
        SHOW_BLOCKS_CHECKBOX: '#show-blocks-checkbox',
        SHOW_ITEMS_CHECKBOX: '#show-items-checkbox',
        SHOW_MOBS_CHECKBOX: '#show-mobs-checkbox',
        SHOW_MOB_VARIANTS_CHECKBOX: '#show-mob-variants-checkbox',
        SHOW_EFFECTS_CHECKBOX: '#show-effects-checkbox',
        SHOW_ENCHANTMENTS_CHECKBOX: '#show-enchantments-checkbox',
        SHOW_ADVANCEMENTS_CHECKBOX: '#show-advancements-checkbox',
        SHOW_PAINTINGS_CHECKBOX: '#show-paintings-checkbox',
        SHOW_BIOMES_CHECKBOX: '#show-biomes-checkbox',
        SHOW_BORDERS_CHECKBOX: '#show-borders-checkbox',
        NAV_PANEL: '#nav-panel',
        NAV_TOGGLE_BTN: '#nav-toggle-btn',
        OVERLAY: '#overlay',
        TOOLTIP: '#tooltip',
        GROWTH_CHART: '#growthChart',
        VIEW_TITLE: '#view-title',
        CONTENT_TABLE_TITLE: '#content-table-title',
        LONGEST_NAMES_TABLE: '#longest-names-table tbody',
        SHORTEST_NAMES_TABLE: '#shortest-names-table tbody',
        CONTENT_TABLE: '#content-table',
    },
};
